/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import static java.sql.JDBCType.NULL;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;

/**
 *
 * @author PC Giang
 */
public class Form_LichSuThuong extends javax.swing.JPanel {

    /**
     * Creates new form Form_LichSuThuong
     */
    public Form_LichSuThuong() {
        initComponents();
                table.addRow(new Object[]{"1", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","3", "20/10/2023",NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"2", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","1", "21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"3", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","5", "21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"4", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","7", "21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"5", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","8","21/10/2023", NULL, NULL,"0", "Đã kết thúc"});
        table.addRow(new Object[]{"6", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","9","21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"7", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","10","21/10/2023", NULL, NULL,"0", "Đã kết thúc"});
        table.addRow(new Object[]{"8", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","11","21/10/2023", NULL, NULL,"0", "Đã kết thúc"});
        table.addRow(new Object[]{"9", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","15","21/10/2023", NULL, NULL,"0", "Đã kết thúc"});
        table.addRow(new Object[]{"10", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","17","21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"11", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","18","21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"12", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","19","21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        table.addRow(new Object[]{"13", "Thưởng học tập kỳ 2023-1", "Thưởng học tập","20","21/10/2023", NULL,NULL, "0", "Đã kết thúc"});
        initComboBoxes();
    }
        private void initComboBoxes() {
        // Thêm JComboBox cho cột Loại
        String[] loaiThuongValues = {"Thưởng học tập", "Thưởng lễ tết"};
        JComboBox<String> loaiThuongComboBox = new JComboBox<>(loaiThuongValues);
        table.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(loaiThuongComboBox));

        // Thêm JComboBox cho cột Trạng thái
        String[] trangThaiValues = {"Ðang phát thưởng", "Ðã kết thúc"};
        JComboBox<String> trangThaiComboBox = new JComboBox<>(trangThaiValues);
        table.getColumnModel().getColumn(8).setCellEditor(new DefaultCellEditor(trangThaiComboBox));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new com.raven.swing.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số", "Tên", "Loại", "Số cán bộ", "Ngày tạo", "Ngày kết thúc", "Ghi chú", "Tổng thưởng", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách khoản thưởng");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.raven.swing.RoundPanel roundPanel1;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
