package com.raven.form.QuanLyThuong;
import java.awt.Container;
import com.raven.model.DanhSachThuongHocTapDAO;
import com.raven.model.DanhSachThuongHocTap;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Form_ThemDanhSachHocTap extends javax.swing.JPanel {
    private Integer ms_kthg;
    private String tenKthg;
    public Form_ThemDanhSachHocTap() {
        initComponents();
        jLabel_HoVaTen.setVisible(false); jLabel_MaHo.setVisible(false); searchText_HoVaTen.setVisible(false); searchText_MaHo.setVisible(false);
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_HuyActionPerformed(evt);
        }
    });
    }
    public Form_ThemDanhSachHocTap(Integer ms_kthg, String tenKthg) {
        this();
        this.ms_kthg = ms_kthg;
        this.tenKthg = tenKthg;
        jLabel_TenKT.setText(tenKthg);
        jLabel_MaSo.setText(String.valueOf(ms_kthg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel_MaSo = new javax.swing.JLabel();
        jLabel_TenKhoanThuong = new javax.swing.JLabel();
        jLabel_HoVaTen = new javax.swing.JLabel();
        searchText_HoVaTen = new com.raven.swing.SearchText();
        jLabel_CCCD = new javax.swing.JLabel();
        jLabel_MaHo = new javax.swing.JLabel();
        jLabel_TruongHoc = new javax.swing.JLabel();
        jLabel_ThanhTich = new javax.swing.JLabel();
        jLabel_MinhChung = new javax.swing.JLabel();
        searchText_CCCD = new com.raven.swing.SearchText();
        searchText_MaHo = new com.raven.swing.SearchText();
        searchText_TruongHoc = new com.raven.swing.SearchText();
        searchText_MinhChung = new com.raven.swing.SearchText();
        jButton_XacNhan = new javax.swing.JButton();
        jButton_Huy = new javax.swing.JButton();
        jLabel_TrangThai = new javax.swing.JLabel();
        jComboBox_TrangThai = new javax.swing.JComboBox<>();
        jComboBox_ThanhTich = new javax.swing.JComboBox<>();
        jLabel_TenKT = new javax.swing.JLabel();
        jLabel_MaSo1 = new javax.swing.JLabel();

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton8.setText("Xuất File");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel_MaSo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_MaSo.setText("Mã số:");

        jLabel_TenKhoanThuong.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_TenKhoanThuong.setText("Tên khoản thưởng:");

        jLabel_HoVaTen.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_HoVaTen.setText("Họ và tên:");

        jLabel_CCCD.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_CCCD.setText("CCCD:");

        jLabel_MaHo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_MaHo.setText("Mã hộ:");

        jLabel_TruongHoc.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_TruongHoc.setText("Trường học:");

        jLabel_ThanhTich.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_ThanhTich.setText("Thành tích:");

        jLabel_MinhChung.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_MinhChung.setText("Minh chứng:");

        jButton_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_XacNhan.setText("Xác nhận");
        jButton_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    // Get input data from GUI fields
                    String cccd = searchText_CCCD.getText();
                    String truongHoc = searchText_TruongHoc.getText();
                    String thanhTich = jComboBox_ThanhTich.getSelectedItem().toString();
                    String minhChung = searchText_MinhChung.getText();
                    String trangThaiPhatThuong = jComboBox_TrangThai.getSelectedItem().toString();

                    // Get ms_kthg and tenKthg from the current form object
                    Integer msKthg = Form_ThemDanhSachHocTap.this.ms_kthg;

                    // Create a new DanhSachThuongHocTap object and set its fields
                    DanhSachThuongHocTap dstht = new DanhSachThuongHocTap();
                    dstht.setMsKThg(msKthg);
                    dstht.setCCCD(cccd);
                    dstht.setTruongHoc(truongHoc);
                    dstht.setThanhTich(thanhTich);
                    dstht.setMinhChung(minhChung);
                    dstht.setTrangThaiPhatThuong(trangThaiPhatThuong);
                    // Assume that the date is set elsewhere or use the current date for ngayThuong
                    dstht.setNgayThuong(new java.util.Date());

                    // Call the method to add the award
                    DanhSachThuongHocTapDAO dao = new DanhSachThuongHocTapDAO();
                    dao.themDanhSachThuongHocTap(dstht);

                    // Display success message
                    JOptionPane.showMessageDialog(null, "Khoản thưởng đã được thêm thành công!");
                } catch (Exception e) {
                    // Display error message
                    JOptionPane.showMessageDialog(null, "Lỗi khi thêm khoản thưởng: " + e.getMessage());
                }
            }
        });



        jButton_Huy.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Huy.setText("Hủy");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });

        jLabel_TrangThai.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_TrangThai.setText("Trạng thái:");

        jComboBox_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã hoàn thành", "Chưa hoàn thành" }));
        jComboBox_TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TrangThaiActionPerformed(evt);
            }
        });

        jComboBox_ThanhTich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học sinh giỏi", "Học sinh tiên tiến", "Thành tích khác" }));

        jLabel_TenKT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_TenKT.setText("jLabel_TenKT");

        jLabel_MaSo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_MaSo1.setText("jLabel_MaSo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_XacNhan)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_HoVaTen)
                            .addComponent(jLabel_CCCD)
                            .addComponent(jLabel_MaHo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_TruongHoc)
                            .addComponent(jLabel_ThanhTich)
                            .addComponent(jLabel_MinhChung)
                            .addComponent(jLabel_TrangThai)
                            .addComponent(jLabel_TenKhoanThuong)
                            .addComponent(jLabel_MaSo))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TenKT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchText_MinhChung, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                .addComponent(jComboBox_ThanhTich, 0, 486, Short.MAX_VALUE)
                                .addComponent(searchText_TruongHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                .addComponent(jComboBox_TrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchText_HoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchText_CCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchText_MaHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel_MaSo1))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenKhoanThuong)
                    .addComponent(jLabel_TenKT))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaSo)
                    .addComponent(jLabel_MaSo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_HoVaTen)
                    .addComponent(searchText_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CCCD)
                    .addComponent(searchText_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaHo)
                    .addComponent(searchText_MaHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TruongHoc)
                    .addComponent(searchText_TruongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ThanhTich)
                    .addComponent(jComboBox_ThanhTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MinhChung)
                    .addComponent(searchText_MinhChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TrangThai)
                    .addComponent(jComboBox_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Huy)
                    .addComponent(jButton_XacNhan))
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XacNhanActionPerformed

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // Lấy ms_kthg và tenKthg từ instance hiện tại
        Integer msKthg = this.ms_kthg;
        String tenKthg = this.tenKthg;

        // Tạo một instance mới của Form_DanhSachThuongHocTap với ms_kthg và tenKthg
        Form_DanhSachThuongHocTap formDanhSachThuongHocTap = new Form_DanhSachThuongHocTap(msKthg, tenKthg);

        // Get the parent container (JFrame or another container)
        Container parentContainer = this.getParent();

        // Remove the current panel (Form_ThemDanhSachHocTap) from the parent container
        parentContainer.remove(this);

        // Add the new panel (Form_DanhSachThuongHocTap) to the parent container
        parentContainer.add(formDanhSachThuongHocTap);

        // Repaint the container to reflect the changes
        parentContainer.revalidate();
        parentContainer.repaint();
    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jComboBox_TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TrangThaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_XacNhan;
    private javax.swing.JComboBox<String> jComboBox_ThanhTich;
    private javax.swing.JComboBox<String> jComboBox_TrangThai;
    private javax.swing.JLabel jLabel_CCCD;
    private javax.swing.JLabel jLabel_HoVaTen;
    private javax.swing.JLabel jLabel_MaHo;
    private javax.swing.JLabel jLabel_MaSo;
    private javax.swing.JLabel jLabel_MaSo1;
    private javax.swing.JLabel jLabel_MinhChung;
    private javax.swing.JLabel jLabel_TenKT;
    private javax.swing.JLabel jLabel_TenKhoanThuong;
    private javax.swing.JLabel jLabel_ThanhTich;
    private javax.swing.JLabel jLabel_TrangThai;
    private javax.swing.JLabel jLabel_TruongHoc;
    private com.raven.swing.SearchText searchText_CCCD;
    private com.raven.swing.SearchText searchText_HoVaTen;
    private com.raven.swing.SearchText searchText_MaHo;
    private com.raven.swing.SearchText searchText_MinhChung;
    private com.raven.swing.SearchText searchText_TruongHoc;
    // End of variables declaration//GEN-END:variables
}
