/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form.QuanLyThuPhi.Phitunguyen;

import Model.NhanKhau.*;
import Model.ThuPhi.*;
import com.raven.form.QuanLyThuPhi.Phitunguyen.Form_DanhSachPhiTuNguyen;
import Model.ThuPhi.Model_ThuPhi;
import Model.ThuPhi.khoan_thu_khac;
import Model.ThuPhi.thu_tien_khac;

import java.awt.Container;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author dangk
 */
public class Form_ThemDongDanhSachTuNguyen extends javax.swing.JPanel {
     Model_ThuPhi myModel;
     khoan_thu_khac myKT;
    /**
     * Creates new form Form_ThemDongDanhSachTuNguyen
     */
    public Form_ThemDongDanhSachTuNguyen(Model_ThuPhi model, khoan_thu_khac kt) {
        myModel=model;
        myKT=kt;
        initComponents();
        jButton_QuayLai.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_QuayLaiActionPerformed(evt);
        }
    });
        
        jLabel_TieuDe.setText(myKT.getTen_KThu());
        
        jButton_XacNhan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if(searchText_MaHo.getText().isEmpty() || searchText_SoTien.getText().isEmpty() ){
                         JOptionPane.showMessageDialog(null,"Hãy nhập đủ các thông tin yêu cầu"); return;
                     }
            if (!myModel.getVal().validate_Ma_Ho(searchText_MaHo.getText()) || !myModel.getVal().validate_int(searchText_SoTien.getText()) ) {
                    JOptionPane.showMessageDialog(null, "Mã hộ không hợp lệ");  // Nhập không đúng định dạng
                    return;
                } else {
                    
                    Model_NhanKhau m = new Model_NhanKhau();
                    ho_gia_dinh family = m.ho_gia_dinh_getfamily(Integer.parseInt(searchText_MaHo.getText()));
                    if (family == null) {
                        JOptionPane.showMessageDialog(null, "Mã hộ này không tồn tại");
                        return;
                    }
            
                 thu_tien_khac tt= new thu_tien_khac();
                 tt.setMS_KThu(myKT.getMS_KThu());
                 tt.setLoai_KThu(myKT.getLoai_KThu());
                 tt.setMa_Ho(Integer.parseInt(searchText_MaHo.getText()));
                 tt.setSo_tien(Integer.parseInt(searchText_SoTien.getText()));
                 tt.setTrangthai_Thu("Đã thu");
                 tt.setNgay_thu(java.sql.Date.valueOf(LocalDate.now()));
                 
                 myModel.thu_tien_ThemDong(tt);
                     
                     
                     JOptionPane.showMessageDialog(null, "Đã thêm hộ đóng góp");
                exit();
        }
    }});
    }
    
    private void exit(){
    Form_DanhSachPhiTuNguyen formDanhSachPhiTuNguyen = new Form_DanhSachPhiTuNguyen(myModel,myKT.getMS_KThu());

    // Get the parent container (JFrame or another container)
    Container parentContainer = this.getParent();

    // Remove the current panel (Form_ThongTinHo) from the parent container
    parentContainer.remove(this);

    // Add the new panel (Form_ThongTinChiTiet) to the parent container
    parentContainer.add(formDanhSachPhiTuNguyen);

    // Repaint the container to reflect the changes
    parentContainer.revalidate();
    parentContainer.repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchText_MaHo = new com.raven.swing.SearchText();
        jButton_QuayLai = new javax.swing.JButton();
        searchText_SoTien = new com.raven.swing.SearchText();
        jButton_XacNhan = new javax.swing.JButton();
        jLabel_SoTien = new javax.swing.JLabel();
        jLabel_TieuDe = new javax.swing.JLabel();
        jLabel_MaHo = new javax.swing.JLabel();

        searchText_MaHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText_MaHoActionPerformed(evt);
            }
        });

        jButton_QuayLai.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_QuayLai.setText("Quay lại");
        jButton_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuayLaiActionPerformed(evt);
            }
        });

        searchText_SoTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText_SoTienActionPerformed(evt);
            }
        });

        jButton_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_XacNhan.setText("Xác nhận");
        jButton_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XacNhanActionPerformed(evt);
            }
        });

        jLabel_SoTien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_SoTien.setText("Số tiền:");

        jLabel_TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TieuDe.setText("Thêm dữ liệu mới cho danh sách");

        jLabel_MaHo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_MaHo.setText("Mã hộ:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_TieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jButton_XacNhan)
                .addGap(15, 15, 15)
                .addComponent(jButton_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_SoTien)
                    .addComponent(jLabel_MaHo))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchText_MaHo, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText_SoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaHo)
                    .addComponent(searchText_MaHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SoTien)
                    .addComponent(searchText_SoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_QuayLai)
                    .addComponent(jButton_XacNhan))
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchText_MaHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText_MaHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText_MaHoActionPerformed

    private void jButton_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayLaiActionPerformed
       exit();
    }//GEN-LAST:event_jButton_QuayLaiActionPerformed

    private void searchText_SoTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText_SoTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText_SoTienActionPerformed

    private void jButton_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_QuayLai;
    private javax.swing.JButton jButton_XacNhan;
    private javax.swing.JLabel jLabel_MaHo;
    private javax.swing.JLabel jLabel_SoTien;
    private javax.swing.JLabel jLabel_TieuDe;
    private com.raven.swing.SearchText searchText_MaHo;
    private com.raven.swing.SearchText searchText_SoTien;
    // End of variables declaration//GEN-END:variables
}
